### ISSUE TITLE
How do I import proj4 in a project?

### ISSUE THREAD

**Issue by magloire** [JeffJacobson/proj4-typescript#1]
Sorry for this question. I am new to typescript. I  have installed the package successfully in a ionic 2 project and imported the package

import 'proj4';

But how do I use it?

When I write:
 let def = proj4('EPSG:4326');

it says: [ts] cannot find name 'proj4'

**Comment by JeffJacobson** [comment]
Don't use mine; It's no longer necessary. You should use the one at https://www.npmjs.com/package/@types/proj4

```console
npm install --save proj4 @types/proj4
```

More info here: http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html

**Comment by spedroq** [comment]
Thanks @JeffJacobson 
@magloire
If you install the types package as Jeff says, you can then import it as follows:
```
import * as proj4 from 'proj4'
```
then use proj4 as in the README

Cheers
